############################
## CHANGE THESE
############################

baseURL: 'https://egt495.github.io/hugoThemes'
title: hugoThemes

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


